# Generated by Django 4.1.7 on 2023-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inputData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('prediction', models.IntegerField()),
            ],
        ),
    ]
