# Generated by Django 4.1.7 on 2023-06-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PII', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdata',
            name='output_text',
        ),
    ]
